BEGIN;


CREATE TABLE IF NOT EXISTS "Funcionarios"(
    "id" SERIALIZABLE PRIMARY KEY NOT NULL,
    "Cargo" VARCHAR(50) DEFAULT NOT NULL,
    "Setor" VARCHAR(50) DEFAULT NOT NULL,
    "Telefone" VARCHAR(20) DEFAULT NOT NULL,
    "Email" VARCHAR(100) DEFAULT NOT NULL,
    "Salário" INTEGER DEFAULT NOT NULL,
    "Nome" VARCHAR(100) DEFAULT NOT NULL
);


CREATE TABLE IF NOT EXISTS "MedVet"(

);


CREATE TABLE IF NOT EXISTS "Consulta"(

);


CREATE TABLE IF NOT EXISTS "Animais"(

);


CREATE TABLE IF NOT EXISTS "Agendamento"(

);

CREATE TABLE IF NOT EXISTS "Tutor"(

);


CREATE TABLE IF NOT EXISTS "Possui"(

);